setwd("C:\\Documents and Settings\\Macro\\Desktop\\Ivandata\\Titanic-Machine-Learning-from-Disaster\\R")
train <- read.csv('train.csv',header=T,stringsAsFactor=F)
test <- read.csv('test.csv',header=T,stringsAsFactor=F)
str(train)
table(train$Survived)
prop.table(table(train$Survived))
test$Survived <- rep(0, 418)
submit <- data.frame(PassengerId = test$PassengerId, Survived = test$Survived)
write.csv(submit, file = "theyallperish.csv", row.names = FALSE)
